# Project information
site_name: Alapakam Notebook
site_url: https://alapakam-dorababu.github.io/alapakam-notebook
site_author: Alapakam Dorababu
site_description: >-
  Alapakam Notebook is my personal space to store coding notes, useful code snippets, and important technical references.  

# Repository
repo_name: alapakam-dorababu/alapakam-notebook
repo_url: https://github.com/alapakam-dorababu/alapakam-notebook

# Copyright
copyright: |
  &copy; 2025 <a href="https://github.com/alapakam-dorababu"  target="_blank" rel="noopener">Alapakam Dorababu</a>

# Configuration
theme:
  name: material
  features:
    - content.tooltips
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.path
    - navigation.tabs.sticky
    - navigation.footer
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  
# Additional configuration
extra:
  #To remove "Made with Material for MkDocs" notice from footer
  # generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/alapakam-dorababu
    - icon: fontawesome/brands/twitter
      link: https://x.com/dorababua67
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    
# Extensions
markdown_extensions:
  # Python Markdown
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true
  
  # Python Markdown Extensions
  pymdownx.betterem:
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  # pymdownx blocks
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    # Custom types
    - info
    - check
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True

  # icons, emoji
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg


# Page tree
nav:
  - Info: index.md
  - Learn: learn/index.md
  - Reference: 
    - Overview: reference/index.md
    - Code Snippets: code-snippets/index.md
  - Knowledge:
    - Overview: knowledge/index.md
    - Docker Commands: docker/docker-commands.md
  - Preparation:
    - Overview: preparation/index.md
    - Python OOPs Interview Questions: preparation/python-oops-interview-questions.md
    - Python Interview Questions for Freshers: preparation/python-interview-questions-for-freshers.md
    - Python Interview Questions for Experienced: preparation/python-interview-questions-for-experienced.md
    - Coding Question:
      - Basic Level: preparation/python-coding-questions-for-basic-level.md
      - intermediate Level: preparation/python-coding-questions-for-intermediate-level.md
      - Advanced Level: preparation/python-coding-questions-for-advanced-level.md
  - About: about.md
  